### PR TITLE
Feature/add overlay layers

### PR DESCRIPTION
**Pull request by mbasa-georepublic**
Changes proposed in this pull request:
- Add Overlay Layers (XYZ, TileWMS, ImageWMS) to map

### CODE REVIEW

**Comment by dkastl** [comment]
Just a reference to the issue: https://github.com/gtt-project/redmine_gtt/issues/101

**Comment by sanak** [comment]
@mbasa-georepublic, @dkastl
Well, I checked this a bit, but overlay layer's outside mask seems to disappear, so that needs to be recovered.

[main] branch
main

[feature/add-overlay-layers] branch
add-overlay-layers

Also, I felt that right side up-down arrows are not necessary, because redmine_gtt plugin supports changing background layer order at `/gtt-tile-souces` view (by right side green up-down arrows).
gtt-tile-sources

So, how about to customize style like the following MapLibre control one ?
https://github.com/dayjournal/maplibre-gl-opacity
Other controls are all black opacity background and white marker, so using similar colors may be also good.

**Comment by sanak** [comment]
@dkastl @mbasa  
Locally, I modified ol-ext LayerSwitcher controls as follows, but are you okay about this change ?
If it's okay, then I will try to apply the changes to redmine_gtt plugin side (S)CSS.
(Note that using browser native checkbox/radio/range seemed to be quite difficult, because it seems to require overriding ol-ext LayerSwitcher implementation as code level, so I gave up that way...)

| [Before (original)] | [After (modified)] |
|---------|--------|
| ol-ext-layerswitcher_before | ol-ext-layerswitcher_after |

Diff (on ol-ext master):
```diff
--- a/src/control/LayerSwitcher.css
+++ b/src/control/LayerSwitcher.css
@@ -179,8 +179,8 @@
   content: '';
 	position: absolute;
 	left: 0.1em; top: 0.1em;
-	width: 1.2em; height: 1.2em; 
-	border: 2px solid #369;
+	width: 1.0em; height: 1.0em; 
+	border: 1px solid #369;
 	background: #fff;
 	box-sizing:border-box;
 }
@@ -192,23 +192,19 @@
 
 .ol-layerswitcher [type="radio"]:checked + label:after {
   background: #369 none repeat scroll 0 0;
-	margin: 0.3em;
+	margin: 0.2em;
 	width: 0.6em;
 	height: 0.6em;
 }
 
 .ol-layerswitcher [type="checkbox"]:checked + label:after {
   background: transparent;
-  border-width: 0 3px 3px 0;
-	border-style: solid;
-	border-color: #369;
-    width: 0.7em;
-    height: 1em;
-    -webkit-transform: rotate(45deg);
-    transform: rotate(45deg);
-    left: 0.55em;
-    top: -0.05em;
-    box-shadow: 1px 0px 1px 1px #fff;
+	border-style: none;
+    width: 0.6em;
+    height: 0.6em;
+    left: 0.3em;
+    top: 0.3em;
+    background-color: #369;
 }
 
 .ol-layerswitcher .panel li.ol-layer-hidden {
@@ -299,23 +295,25 @@
 	opacity: 0.5;
 	cursor: move;
 	cursor: ns-resize;
+	border-radius: 10px;
 }
 
 .ol-layerswitcher .layerup:before,
 .ol-layerswitcher .layerup:after {
-  border-color: #fff transparent;
+  border-color: #fff;
 	border-style: solid;
-	border-width: 0.4em 0.4em 0;
+	border-width: 0 0 0.15em 0.15em;
 	content: "";
-	height: 0;
+	height: 0.3em;
 	position: absolute;
-	bottom: 3px;
-	left: 0.1em;
-	width: 0;
+	bottom: 5px;
+	left: 0.3em;
+	width: 0.3em;
+	transform: rotate(-45deg)
 }
 .ol-layerswitcher .layerup:after {
-  border-width: 0 0.4em 0.4em;
-	top:3px;
+  border-width: 0.15em 0.15em 0 0;
+	top:5px;
 	bottom: auto;
 }
 
@@ -423,17 +421,13 @@
 
 .ol-layerswitcher .layerswitcher-opacity {
   position:relative;
-	border: 1px solid #369;
-	height: 3px;
+	height: 5px;
 	width: 120px;
 	margin:5px 1em 10px 7px;
 	box-sizing: border-box;
 	border-radius: 3px;
 	background: #69c;
-	background: -webkit-linear-gradient(left, rgba(0,60,136,0), rgba(0,60,136,0.6));
-	background: linear-gradient(to right, rgba(0,60,136,0), rgba(0,60,136,0.6));
 	cursor: pointer;
-	box-shadow: 1px 1px 1px rgba(0,0,0,0.5);
 }
 
 .ol-layerswitcher .layerswitcher-opacity .layerswitcher-opacity-cursor,

```

**Comment by dkastl** [comment]
Maybe I'm not seeing all the changes, but is it just the rounded controls and different checkbox? I think it's OK, but I would say we try the sidebar next to have all this look a bit more consistent.

**Comment by sanak** [comment]
@dkastl  
> but is it just the rounded controls and different checkbox?

Yes, finally...

> I think it's OK, but I would say we try the sidebar next to have all this look a bit more consistent.

Okay, thanks for confirmation.
It may be good to create the new issue for the sidebar things, later.

**Comment by sanak** [comment]
I just rebased from the latest main branch and renamed migration file name.

I will check overlay functionality and apply style adjustment (https://github.com/gtt-project/redmine_gtt/pull/102#issuecomment-922649918) until tomorrow.

**Comment by sanak** [comment]
Sorry for delaying about this.
I will not apply style adjustment, but I will delete vertical layer drag handler at the right side.
 ol-ext-layerswitcher_before

**Comment by sanak** [comment]
> I will delete vertical layer drag handler at the right side.

I supported above on the latest commit, but I noticed that layer ordering is reverse from original main branch, so I will fix it also.

**Comment by sanak** [comment]
> I noticed that layer ordering is reverse from original main branch, so I will fix it also.

Well, this seems to be spec on ol-ext LayerPopup (1st top, last bottom) and LayerSwitcher (1st bottom, last top) from the following examples code.
- https://viglino.github.io/ol-ext/examples/control/map.switcher.popup.html
- https://viglino.github.io/ol-ext/examples/control/map.switcher.html

I will keep this as it is now.

**Comment by sanak** [comment]
@dkastl @mbasa-georepublic @smellman 
For `ol.source.TileWMS` and `ol.source.ImageWMS` testing, the following options can be used. (Need to move to US to see the layers.)

---

`ol.source.TileWMS`
https://openlayers.org/en/latest/examples/wms-tiled.html
```json
{
  "url": "https://ahocevar.com/geoserver/wms",
  "params": {"LAYERS": "topp:states", "TILED": true},
  "serverType": "geoserver",
  "transition": 0
}
```

`ol.source.ImageWMS`
https://openlayers.org/en/latest/examples/wms-image.html
```json
{
  "url": "https://ahocevar.com/geoserver/wms",
  "params": {"LAYERS": "topp:states"},
  "ratio": 1,
  "serverType": "geoserver"
}
```

---

I fixed `ImageWMS` rendering issue on the last commit (https://github.com/gtt-project/redmine_gtt/commit/465be3f9994f417af5e5cc35c21b967c0b24c5f1), so checking it is helpful.

**Pull request merged**
