### PR TITLE
Ftr/next gtt layers

### PR DESCRIPTION
**Pull request by dkastl**
Changes proposed in this pull request:
- Changes "Tile Sources" to "Map Layers" (-> breaking change)
- Support of layers, sources and formats
- Adds notification when no basemap available
- ...

### CODE REVIEW

**Comment by dkastl** [comment]
@sanak @smellman , I would like to merge this branch into `next` and prepare then for a next major release. This branch actually includes the changes of two other branches already: https://github.com/gtt-project/redmine_gtt/pull/231 and https://github.com/gtt-project/redmine_gtt/pull/227

This branch contains a lot of refactoring and also some bigger changes, so I would like to make this a new major version: v5.0.0. I also think it's OK to require Redmine 5 or higher, not because it maybe won't work anymore with v4, but I think we shouldn't spend much resources on supporting years old versions.

Could you check if you experience issues with this branch. If not, let's merge it into `next`. I'm not sure I can complete the Geocoding related issues until FOSS4G. If not let's release v5.0.0 and do the geocoding improvements for v5.1.0.

**Comment by dkastl** [comment]
The following change in `init.rb` made GH Actions fail for Redmine 4.2 https://github.com/gtt-project/redmine_gtt/pull/233/commits/3228d6256efd90b6979f9d902a275f74856107e2

So I reverted the changes to set the minimum version until we agree on this.

**Comment by sanak** [comment]
@dkastl (CC: @smellman)  
I am okay to drop Redmine 4.2 support, because Ruby 2.7 is already EOL.
- https://github.com/docker-library/redmine/issues/289
- [Feature #38585: Drop Ruby 2.7 support and set Redmine 4.2 as EOL - Redmine](https://www.redmine.org/issues/38585)

Related with CI Redmine 4.2 error, it's okay to adjust CI side, but later (after this PR merge) may be better.

Also, documentation updates can be done later (after this PR merge).
- https://github.com/gtt-project/redmine_gtt/blob/ftr/next-gtt-layers/README.md#how-to-use
- https://github.com/gtt-project/redmine_gtt/blob/ftr/next-gtt-layers/doc/getting-started.md#tile-source

So, I approve this.

**Review by sanak — APPROVED** [review]
Thanks a lot! 👍🙇

**Pull request merged**
