### PR TITLE
Adds target control

### LINKED ISSUE #300: Target cross control
Having a target symbol in the map center can be a helpful indicator.

Let's make it a configurable map control:
https://viglino.github.io/ol-ext/examples/canvas/map.target.control.html

### PR DESCRIPTION
**Pull request by dkastl**
Fixes #300 .

Changes proposed in this pull request:
- Adds target control
- Adds plugin settings to enable/disable target control

### CODE REVIEW

**Review by sanak — CHANGES_REQUESTED** [review]
I confirmed that it works correctly on my PC (macOS) Chrome,
but the target control size was larger on mobile iPhone Safari and Android Chrome.
It would be nice to have same size as pc in mobile browsers.

| PC (macOS+Chrome) | iPhone (Safari) | Android (Chrome) |
|-----------------------|----------------|-------------------|
| gtt-target-control-on-pc | gtt-target-control-on-iphone | gtt-target-control-on-android |

**Comment by dkastl** [comment]
I see. Thanks for checking on mobile. I didn't do this.

Since this comes from ol-ext, I'm not sure if this can be solved without upstream changes, but I will try. It actually uses OpenLayers style to draw the plus sign, so I'm wondering how ol.style examples look on mobile devices.

**Comment by dkastl** [comment]
This adjustment should solve the scaling on high DPI devices: https://github.com/gtt-project/redmine_gtt/pull/301/commits/6814209ff627635c2c7e76ba24e29688da2174a2

**Review by sanak — APPROVED** [review]
Thanks!
I confirmed that target control size is good in PC Chrome, iPhone Safari and Android Chrome.

**Pull request merged**
