### PR TITLE
Updates API endpoints

### PR DESCRIPTION
**Pull request by dkastl**
@sanak @smellman , I realized that API endpoint changes in upstream Redmine have not been applied for some time, because this plugin completely replaces these endpoints to add the geometry information.

This pull request brings these API endpoints up-to-date:
- Issues
- Projects
- Users

### CODE REVIEW

**Comment by sanak** [comment]
@dkastl Okay, thanks!
Currently, `README.md` mentions that `Redmine >= 4.2.0` is minimum requirement, but with this changes, the requirement needs to be updated to `Redmine >= 5.0.0` or something ?

**Comment by sanak** [comment]
If possible, removing all `*.api.rsb` override will be the best by something like the following patch, but it may be really far future... 😅
- [Feature #31521: Make REST API for users incremental with plugins - Redmine](https://www.redmine.org/issues/31521)

**Comment by sanak** [comment]
@dkastl Okay, I see.
Then let's drop older Redmine version.
Will you update `README.md` in another PR ?
Anyway, I will check the diff more, later.

**Review by smellman — APPROVED** [review]
LGTM

**Review by sanak — APPROVED** [review]
I confirmed that the following local diffs are basically same, so I approve this.
```sh
git diff 4.0.0..5.0.0 app/views/issues/index.api.rsb
git diff 4.0.0..5.0.0 app/views/issues/show.api.rsb
git diff 4.0.0..5.0.0 app/views/projects/index.api.rsb
git diff 4.0.0..5.0.0 app/views/projects/show.api.rsb
git diff 4.0.0..5.0.0 app/views/users/index.api.rsb
git diff 4.0.0..5.0.0 app/views/users/show.api.rsb
```
Thanks!

**Comment by sanak** [comment]
@dkastl 
> So does this mean Redmine 4.2 as a minimum version is still OK? That's perfect!

Oh, Redmine minimum version should be 5.0, I think.
(I haven't checked Redmine 4.2 compatibility.)
I don't know whether CI test covers that, so probably it's better to run CI, once.

**Comment by sanak** [comment]
@dkastl Could you change CI workflow file as follows, once ?
```diff
--- a/.github/workflows/test-postgis.yml
+++ b/.github/workflows/test-postgis.yml
@@ -7,11 +7,11 @@ on:
   push:
     branches:
       - main
-      - master
+      - next
   pull_request:
     branches:
       - main
-      - master
+      - next
 
 jobs:
   test:
```

**Comment by sanak** [comment]
> With `once` you mean temporarily? I would say it's good to run with `next` branch and `master` isn't there anymore.

Oh, sure. It should not be `once`. 😅

And the result seems to be no problem, so I think that Redmine 4.2 is still supported. 😄

**Pull request merged**
